import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowRight, Check, ChevronRight } from "lucide-react";
import { Button } from "@/components/ui/button";
import { ArticleGrid, ContactDetails, ContactForm, CTASection, FAQList, GalleryGrid, SectionHeading, ServicesGrid, TestimonialCards } from "@/components/site-components";
import { benefits, images, process, site } from "@/lib/site-data";

export const Route = createFileRoute("/")({
  head: () => ({ meta: [{title:"Dr. Abdullah — Personalized Physiotherapy"},{name:"description",content:"Personalized, evidence-informed physiotherapy and rehabilitation care with Dr. Abdullah."},{property:"og:title",content:"Dr. Abdullah — Personalized Physiotherapy"},{property:"og:description",content:"Move better with focused, patient-centered physiotherapy care."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"}], links:[{rel:"canonical",href:"/"}], scripts:[{type:"application/ld+json",children:JSON.stringify({"@context":"https://schema.org","@type":"Physician",name:"Dr. Abdullah",medicalSpecialty:"Physiotherapy",telephone:"[PHONE NUMBER]",email:"[EMAIL]",areaServed:"[LOCATION]"})}] }),
  component: HomePage,
});

function HomePage() { return <>
  <section className="relative overflow-hidden bg-surface"><div className="container-site grid items-center gap-12 py-12 lg:min-h-[720px] lg:grid-cols-[1.05fr_.95fr] lg:py-16"><div className="animate-rise"><p className="eyebrow">Dr. Abdullah · Physiotherapist</p><h1 className="mt-5 text-balance text-5xl font-extrabold leading-[1.08] text-navy sm:text-6xl lg:text-7xl">Move Better. Recover Stronger. <span className="text-primary">Live Without Limits.</span></h1><p className="mt-6 max-w-xl text-lg leading-8 text-muted-foreground">Personalized physiotherapy and rehabilitation care designed to help you recover, move confidently, and get back to the life you enjoy.</p><div className="mt-8 flex flex-wrap gap-3"><Button size="lg" asChild><Link to="/contact">Book a Consultation <ArrowRight/></Link></Button><Button size="lg" variant="outline" asChild><Link to="/services">Explore Services</Link></Button></div><div className="mt-8 flex flex-wrap gap-x-6 gap-y-3 border-t border-border pt-6">{["Personalized Care","Evidence-Informed Treatment","Patient-Focused Approach"].map(x=><span key={x} className="flex items-center gap-2 text-xs font-semibold text-muted-foreground"><Check className="size-4 text-teal"/>{x}</span>)}</div></div><div className="relative mx-auto w-full max-w-lg self-end"><div className="absolute -left-4 top-12 hidden border-l-2 border-primary bg-card p-4 shadow-lg sm:block"><p className="text-xs font-bold text-primary">CARE, BUILT AROUND YOU</p><p className="mt-1 text-xs text-muted-foreground">Assessment · Plan · Progress</p></div><img src={images.portrait} alt="Illustrative professional portrait representing Dr. Abdullah in a physiotherapy clinic" width="1280" height="1600" fetchPriority="high" className="max-h-[620px] w-full rounded-t-[2rem] object-cover object-top shadow-2xl"/><p className="bg-navy p-3 text-center text-xs text-primary-foreground/70">Illustrative portrait — replace with Dr. Abdullah’s approved professional photograph.</p></div></div></section>
  <section className="border-y border-border bg-card"><div className="container-site grid divide-y divide-border py-7 sm:grid-cols-3 sm:divide-x sm:divide-y-0">{[["01","Listen first"],["02","Plan together"],["03","Progress with purpose"]].map(([n,t])=><div key={n} className="flex items-center gap-4 px-5 py-3"><span className="text-sm font-extrabold text-primary">{n}</span><span className="font-bold text-navy">{t}</span></div>)}</div></section>
  <section className="section-space"><div className="container-site grid items-center gap-14 lg:grid-cols-2"><div className="relative"><img src={images.treatment} alt="Illustrative physiotherapy movement assessment" loading="lazy" width="1600" height="1072" className="aspect-[4/3] w-full rounded-md object-cover"/><div className="absolute -bottom-5 right-5 max-w-xs rounded-md bg-navy p-5 text-primary-foreground shadow-xl"><p className="text-sm font-bold">Professional profile</p><p className="mt-1 text-xs text-primary-foreground/65">{site.qualifications} · {site.experience}</p></div></div><div><SectionHeading eyebrow="About Dr. Abdullah" title="Clinical care with a distinctly personal approach." text="Dr. Abdullah’s approach is designed around listening carefully, assessing thoroughly and helping each person understand their path forward. Every plan begins with the individual—not a one-size-fits-all protocol."/><div className="mt-7 grid gap-4 sm:grid-cols-2">{["Clear, practical guidance","Goals that matter to you","Progressive rehabilitation","Long-term movement confidence"].map(x=><p key={x} className="flex items-center gap-2 text-sm font-semibold"><Check className="size-4 text-teal"/>{x}</p>)}</div><Button asChild variant="outline" size="lg" className="mt-8"><Link to="/about">Learn More About Dr. Abdullah <ChevronRight/></Link></Button></div></div></section>
  <section className="section-space bg-surface"><div className="container-site"><SectionHeading eyebrow="Areas of care" title="Physiotherapy designed around real-life goals." text="These are editable example services. Confirm the final list with Dr. Abdullah before publishing."/><ServicesGrid limit={8}/><div className="mt-10 flex flex-col items-start justify-between gap-4 border-t border-border pt-8 sm:flex-row sm:items-center"><p className="font-bold text-navy">Not sure which treatment you need?</p><Button asChild variant="outline"><Link to="/contact">Contact Dr. Abdullah <ArrowRight/></Link></Button></div></div></section>
  <section className="section-space"><div className="container-site"><SectionHeading eyebrow="Why choose Dr. Abdullah" title="Thoughtful care. Clear direction. Your goals at the center." center/><div className="mt-12 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{benefits.map(({title,text,icon:Icon})=><article key={title} className="border border-border bg-card p-6"><Icon className="size-6 text-primary"/><h3 className="mt-5 font-bold text-navy">{title}</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">{text}</p></article>)}</div></div></section>
  <section className="section-space bg-navy text-primary-foreground"><div className="container-site"><SectionHeading eyebrow="Your treatment journey" title="A clear process, from first conversation to confident movement."/><div className="mt-14 grid gap-px overflow-hidden rounded-md bg-primary-foreground/15 lg:grid-cols-5">{process.map(([n,t,d])=><article key={n} className="bg-navy p-6"><span className="text-3xl font-extrabold text-teal">{n}</span><h3 className="mt-8 font-bold">{t}</h3><p className="mt-3 text-sm leading-6 text-primary-foreground/65">{d}</p></article>)}</div></div></section>
  <section className="section-space"><div className="container-site"><SectionHeading eyebrow="Recovery journeys" title="Care in motion, shown with dignity and consent." text="The images shown are illustrative. Only publish real patient sessions, progress photographs or stories with explicit written consent and appropriate privacy safeguards."/><GalleryGrid limit={3}/></div></section>
  <section className="section-space bg-surface"><div className="container-site"><SectionHeading eyebrow="Patient feedback" title="The standard of care, in patients’ own words." text="The examples below are clearly marked demo content and must be replaced with genuine, consented reviews."/><TestimonialCards/></div></section>
  <section className="section-space"><div className="container-site"><div className="flex items-end justify-between gap-4"><SectionHeading eyebrow="From the journal" title="Practical guidance for better movement."/><Button asChild variant="outline" className="hidden sm:inline-flex"><Link to="/blog">View all articles</Link></Button></div><ArticleGrid limit={3}/></div></section>
  <section className="section-space bg-surface"><div className="container-site"><SectionHeading eyebrow="Frequently asked" title="Helpful answers before your first visit."/><FAQList/></div></section>
  <CTASection/>
  <section className="section-space"><div className="container-site grid gap-14 lg:grid-cols-[.75fr_1.25fr]"><div><SectionHeading eyebrow="Contact" title="Let’s discuss your next step." text="Share a little about what you need. Dr. Abdullah can then confirm availability and whether the service may be suitable."/><div className="mt-8"><ContactDetails/></div></div><div className="rounded-md border border-border bg-card p-6 shadow-lg sm:p-9"><ContactForm/></div></div></section>
  </> }