import { Link } from "@tanstack/react-router";
import { useState, type FormEvent, type ReactNode } from "react";
import { ArrowRight, CheckCircle2, Clock3, Mail, MapPin, Phone, Quote, Star } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";
import { articles, faqs, gallery, services, site, type Service } from "@/lib/site-data";

export function SectionHeading({eyebrow,title,text,center=false}:{eyebrow:string;title:string;text?:string;center?:boolean}) { return <div className={center?"mx-auto max-w-2xl text-center":"max-w-2xl"}><p className="eyebrow">{eyebrow}</p><h2 className="mt-4 text-balance text-3xl font-extrabold leading-tight text-navy sm:text-4xl lg:text-5xl">{title}</h2>{text&&<p className="mt-5 text-base leading-7 text-muted-foreground">{text}</p>}</div> }
export function PageHero({eyebrow,title,text,children}:{eyebrow:string;title:string;text:string;children?:ReactNode}) { return <section className="border-b border-border bg-surface"><div className="container-site py-16 sm:py-24"><p className="eyebrow">{eyebrow}</p><h1 className="mt-5 max-w-4xl text-balance text-4xl font-extrabold leading-tight text-navy sm:text-6xl">{title}</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-muted-foreground">{text}</p>{children}</div></section> }
export function ServiceCard({service}:{service:Service}) { const Icon=service.icon; return <article className="group border-t-2 border-primary bg-card p-7 shadow-sm transition duration-300 hover:-translate-y-1 hover:shadow-lg"><span className="grid size-11 place-items-center rounded-md bg-secondary text-primary"><Icon className="size-5"/></span><h3 className="mt-7 text-xl font-bold text-navy">{service.title}</h3><p className="mt-3 min-h-20 text-sm leading-7 text-muted-foreground">{service.description}</p><Link to="/contact" className="mt-5 inline-flex items-center gap-2 text-sm font-bold text-primary">Learn more <ArrowRight className="size-4 transition-transform group-hover:translate-x-1"/></Link></article> }
export function ServicesGrid({limit}:{limit?:number}) { return <div className="mt-12 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{services.slice(0,limit).map(s=><ServiceCard key={s.title} service={s}/>)}</div> }
export function GalleryGrid({limit}:{limit?:number}) { return <div className="mt-12 grid auto-rows-[230px] gap-4 sm:grid-cols-2 lg:grid-cols-3">{gallery.slice(0,limit).map((item,i)=><figure key={item.title} className={`group relative overflow-hidden rounded-md bg-muted ${i===0?"sm:row-span-2 lg:col-span-2":""}`}><img src={item.src} alt={item.alt} loading="lazy" width="1600" height="1072" className="h-full w-full object-cover transition duration-500 group-hover:scale-[1.03]"/><figcaption className="absolute inset-x-0 bottom-0 bg-navy/85 p-5 text-primary-foreground"><span className="text-[10px] font-bold uppercase tracking-[.12em] text-primary-foreground/70">{item.category}</span><p className="mt-1 font-bold">{item.title}</p></figcaption></figure>)}</div> }
export function ArticleGrid({limit}:{limit?:number}) { return <div className="mt-12 grid gap-6 md:grid-cols-3">{articles.slice(0,limit).map(a=><article key={a.slug} className="overflow-hidden rounded-md border border-border bg-card shadow-sm"><img src={a.image} alt="Illustrative physiotherapy editorial" loading="lazy" width="1600" height="1072" className="aspect-[16/10] w-full object-cover"/><div className="p-6"><p className="eyebrow">{a.category}</p><h3 className="mt-3 text-xl font-bold leading-snug text-navy">{a.title}</h3><p className="mt-3 text-sm leading-6 text-muted-foreground">{a.description}</p><div className="mt-5 flex items-center justify-between border-t border-border pt-4 text-xs text-muted-foreground"><span>{a.date}</span><Link to="/blog/$slug" params={{slug:a.slug}} className="font-bold text-primary">Read more</Link></div></div></article>)}</div> }
export function FAQList() { return <Accordion type="single" collapsible className="mt-10"><div className="grid gap-x-10 lg:grid-cols-2">{faqs.map(([q,a],i)=><AccordionItem value={`faq-${i}`} key={q}><AccordionTrigger className="py-6 text-base text-navy hover:no-underline">{q}</AccordionTrigger><AccordionContent className="pb-6 leading-7 text-muted-foreground">{a}</AccordionContent></AccordionItem>)}</div></Accordion> }
export function ContactForm() { const [sent,setSent]=useState(false); function submit(e:FormEvent){e.preventDefault();setSent(true)} if(sent)return <div className="rounded-md border border-primary/30 bg-secondary p-8 text-center"><CheckCircle2 className="mx-auto size-10 text-primary"/><h3 className="mt-4 text-xl font-bold text-navy">Request prepared</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">This demo form is not connected yet. Add your real contact details or message service before publishing.</p><Button variant="outline" className="mt-5" onClick={()=>setSent(false)}>Send another</Button></div>; return <form onSubmit={submit} className="grid gap-5" aria-label="Consultation request"><div className="grid gap-5 sm:grid-cols-2"><Field label="Full Name"><Input required placeholder="Your full name"/></Field><Field label="Phone Number"><Input required type="tel" placeholder="Your phone number"/></Field><Field label="Email"><Input required type="email" placeholder="you@example.com"/></Field><Field label="Preferred Contact Method"><select required className="h-11 w-full rounded-md border border-input bg-background px-3 text-sm focus:outline-none focus:ring-2 focus:ring-ring"><option value="">Choose one</option><option>Phone</option><option>WhatsApp</option><option>Email</option></select></Field></div><Field label="Reason for Consultation"><Input required placeholder="Brief reason for your enquiry"/></Field><Field label="Message"><Textarea required className="min-h-32" placeholder="Tell Dr. Abdullah how he may help"/></Field><p className="text-xs leading-5 text-muted-foreground">Please do not include urgent or highly sensitive medical information. This form is not for emergencies.</p><Button size="lg" type="submit">Request a Consultation <ArrowRight/></Button></form> }
function Field({label,children}:{label:string;children:ReactNode}) { return <label className="grid gap-2 text-sm font-semibold text-navy"><span>{label}</span>{children}</label> }
export function ContactDetails() { return <div className="space-y-4">{[[Phone,"Phone",site.phone],[Mail,"Email",site.email],[MapPin,"Service area",site.location]].map(([Icon,label,value])=><div key={String(label)} className="flex gap-4 border-b border-border pb-4"><span className="grid size-10 shrink-0 place-items-center rounded-md bg-secondary text-primary"><Icon className="size-4"/></span><div><p className="text-xs font-bold uppercase tracking-[.1em] text-muted-foreground">{String(label)}</p><p className="mt-1 font-semibold text-navy">{String(value)}</p></div></div>)}</div> }
export function TestimonialCards() { const items=["Dr. Abdullah explained everything clearly and helped me understand each step of the plan.","The one-to-one approach made the rehabilitation process feel focused and manageable.","I appreciated the clear guidance and practical exercises for daily life."]; return <div className="mt-12 grid gap-5 md:grid-cols-3">{items.map((text,i)=><article key={i} className="rounded-md border border-border bg-card p-7"><div className="flex items-center justify-between"><Quote className="size-7 text-primary"/><span className="flex text-primary" aria-label="5 star demonstration rating">{[1,2,3,4,5].map(n=><Star key={n} className="size-3 fill-current"/>)}</span></div><p className="mt-6 leading-7 text-foreground">“{text}”</p><div className="mt-6 border-t border-border pt-4"><p className="text-sm font-bold text-navy">Demo patient name</p><p className="mt-1 text-xs text-muted-foreground">Placeholder review — replace with consent</p></div></article>)}</div> }
export function CTASection() { return <section className="bg-primary py-16 text-primary-foreground"><div className="container-site flex flex-col items-start justify-between gap-8 md:flex-row md:items-center"><div><p className="text-xs font-bold uppercase tracking-[.14em] text-primary-foreground/70">Take the next step</p><h2 className="mt-3 text-3xl font-extrabold sm:text-4xl">Ready to start your recovery?</h2><p className="mt-3 max-w-xl text-primary-foreground/75">Begin with a conversation about your goals and what personalized physiotherapy could look like.</p></div><Button asChild size="lg" variant="secondary"><Link to="/contact">Book a consultation <ArrowRight/></Link></Button></div></section> }